import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import SideNav from '../components/SideNav'
import TopNav from '../components/TopNav'
import WelcomeComponent from '../components/WelcomeComponent'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-row'>
        <SideNav/>

        <div className='w-full'>
          <TopNav/>
          <WelcomeComponent/>
          <div className='m-8'>
            <h2 className='text-xl font-medium'>
              Upcoming Events
            </h2>
          </div>

          <div className='m-8'>
            <h2 className='text-xl font-medium'>
              Past Events
            </h2>
          </div>
        </div>
      </main>
    </>
  )
}
