import React from 'react'
import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import SideNav from '../components/SideNav'
import WelcomeComponent from '../components/WelcomeComponent'


export default function Home() {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  const toggleNav = () => {
    console.log('changing nav toggle');
    setIsOpen(!isOpen);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col lg:flex-row'>
        <SideNav isOpen={isOpen} toggleNav={toggleNav} />
        <div className={' h-12'}>
          <button onClick={() => {
            console.log('clicked');
            
            toggleNav();
          }}>
            Something
            <span className="material-symbols-outlined">menu</span>
          </button>
        </div>
        <div className='w-full'>
          <WelcomeComponent />
          <div className='m-8'>
            <h2 className='text-xl font-medium'>
              Upcoming Events
            </h2>
          </div>

          <div className='m-8'>
            <h2 className='text-xl font-medium'>
              Past Events
            </h2>
          </div>
        </div>
      </main>
    </>
  )
}
